[toolchain]
anchor_version = "1.0.1"
solana_version = "3.1.15"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
aegis = "3z9GuipayYpAcPnjiwFkfe6gZvfSfuPZgX8djYu67Yhd"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
